version: "3.8"

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
  app:
    container_name: app
    build: .
    command: bash -c "uvicorn src.admin.start:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis

  celery:
    build: .
    command: celery -A src.views_service.tasks:celery_app worker -l info
    volumes:
      - .:/app
    depends_on:
      - app
      - redis

  celery-beat:
    build: .
    command: celery -A src.views_service.tasks:celery_app beat -l info
    volumes:
      - .:/app
    depends_on:
      - app
      - redis